### ISSUE TITLE
pred_unlabeled_roberta-base_temp{template_id}.npy ，how to create？

### ISSUE THREAD

**Issue by datalee** [yueyu1030/Patron#1]
rt

**Comment by yueyu1030** [comment]
Thanks for reaching out. The corresponding files have been uploaded to the [google drive](https://drive.google.com/drive/folders/1qSGGxVlxmy1-T1RLDlwGlGHKrw2kEKKm). The code for calculating prompt-based predictions is based on the original PET repo (https://github.com/timoschick/pet). We will release the code for generating prompt-based predictions later (Currently this paper is still under submission).

**Comment by datalee** [comment]
![image](https://user-images.githubusercontent.com/13651873/195288524-ba3459ad-66ae-4a19-92e0-cb77384e18bc.png)

`    if prop: 
        index = faiss.IndexFlatL2(d) 
        index.add(unlabeled_feat)
        D, I = index.search(unlabeled_feat, k+1) 
        prop_score = np.mean(unlabel_value[I] * np.exp(-D*rho), axis=-1)`

prop_score  in the code lacks u(x)
![image](https://user-images.githubusercontent.com/13651873/195289191-e16e3a42-7fac-4019-91d1-2032732aa0a6.png)
 in  Eq.(7)?

**Comment by datalee** [comment]
![image](https://user-images.githubusercontent.com/13651873/195293340-48cf1d77-ca75-458e-aaa3-8bea16f3ea34.png)
another question:
1 and 2 in the picture have different orders of magnitude, 1 is (0, 0.1), and 2 is (7, 19)， so Does this add up mean nothing?

**Comment by yueyu1030** [comment]
Thanks for pointing this out. I found there exists some mismatch between our original implementation and the code. 1) for u(x), you need to add the original uncertainty u(x) after the propagated one; 2) for Eq 8, the term $u_{prop}$ is useful as shown in our parameter study. This term will be helpful in determining the selected samples with higher propagated uncertainty.  
Also, the term should be $\beta||z_j-\bar{z}_i||_2$ instead of $\beta||z_j-\bar{z}_i||_2^2$. We will modify our manuscript.

**Comment by yueyu1030** [comment]
By the way, we have also tried to set a very small $\beta$ (e.g. $\beta=0.01$ or even smaller) but found the final result is not very stable.
